CREATE TABLE IF NOT EXISTS leads (
  id TEXT PRIMARY KEY NOT NULL,
  submission_key TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  name TEXT NOT NULL,
  company TEXT NOT NULL,
  email TEXT NOT NULL,
  country TEXT NOT NULL,
  cf_country TEXT,
  phone TEXT,
  application TEXT NOT NULL,
  timeline TEXT,
  message TEXT NOT NULL,
  product_slug TEXT,
  solution_slug TEXT,
  application_slug TEXT,
  page_path TEXT NOT NULL,
  source_component TEXT NOT NULL,
  locale TEXT NOT NULL DEFAULT 'en',
  referrer TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  consent_at TEXT NOT NULL,
  icp_decision TEXT NOT NULL,
  icp_top_match TEXT,
  icp_score INTEGER,
  icp_band TEXT,
  icp_rule_version TEXT NOT NULL,
  icp_snapshot TEXT NOT NULL,
  notification_status TEXT NOT NULL DEFAULT 'pending' CHECK (notification_status IN ('pending', 'sent', 'failed')),
  notification_attempts INTEGER NOT NULL DEFAULT 0,
  notification_error TEXT,
  notification_started_at TEXT,
  notified_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at);
CREATE INDEX IF NOT EXISTS idx_leads_notification_status_created_at ON leads(notification_status, created_at);
